name: test

on:
  push:
  pull_request:

jobs:
  update-nightly-tag:
    name: Update nightly release tag
    runs-on: ubuntu-22.04
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    permissions:
        contents: write
    steps:
      - uses: actions/checkout@v5
      - name: Move nightly tag to head for nightly release
        run: git tag -f nightly && git push origin nightly -f

  build-nightly-artifact:
    name: Nightly Artifact Build
    runs-on: ubuntu-latest
    needs: [update-nightly-tag]
    if: |
      always() &&
      (needs.update-nightly-tag.result == 'success' ||
        needs.update-nightly-tag.result == 'skipped')
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v5
      - name: install dependencies
        run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          ca-certificates \
          libconfig-dev \
          libopus-dev \
          libsodium-dev \
          libvpx-dev \
          pkg-config \
          libavutil-dev \
          libavcodec-dev \
          libavformat-dev \
          libavdevice-dev \
          libavfilter-dev \
          libswresample-dev \
          libswscale-dev \
          libx264-dev \
          libx11-dev

      - name: compile binary
        run: |
          gcc -O3 -g -fPIC tox_videoplayer.c $(pkg-config --cflags --libs x11 libsodium libswresample opus vpx libavcodec libswscale libavformat libavdevice libavutil x264) -pthread -o tox_videoplayer

      - name: Rename artifact for nightly upload
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        run: |
          cp ./tox_videoplayer tox_videoplayer_nightly
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: tox_videoplayer_nightly
          path: tox_videoplayer_nightly
      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.event_name == 'push' && github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "tox_videoplayer_nightly"

  test:
    runs-on: ubuntu-22.04
    steps:
      - uses: actions/checkout@v5
      - name: install dependencies
        run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          ca-certificates \
          libconfig-dev \
          libopus-dev \
          libsodium-dev \
          libvpx-dev \
          pkg-config \
          libavutil-dev \
          libavcodec-dev \
          libavformat-dev \
          libavdevice-dev \
          libavfilter-dev \
          libswresample-dev \
          libswscale-dev \
          libx264-dev \
          libx11-dev \
          libasan6

      - name: compile binary
        run: |
          gcc -O3 -g -fPIC tox_videoplayer.c $(pkg-config --cflags --libs x11 libsodium libswresample opus vpx libavcodec libswscale libavformat libavdevice libavutil x264) -pthread -o tox_videoplayer

      - name: check binary
        run: |
          ldd tox_videoplayer
          ls -al tox_videoplayer
          ls -hal tox_videoplayer

      - name: Run the test
        run: |
          ./tox_videoplayer -v
